name: Check compilation of other packages

on:
  schedule:
    - cron: '42 4 * * *'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        # Please keep the list in sync with the minimal version of OCaml in
        # dune-project, dune.opam.template and bootstrap.ml
        ocaml-version:
          - 4.10.0
        skip_test:
          - false
        include:
          - ocaml-version: 4.11.0
            os: ubuntu-latest
            skip_test: true
          - ocaml-version: 4.09.1
            os: ubuntu-latest
            skip_test: true
          - ocaml-version: 4.08.1
            os: ubuntu-latest
            skip_test: true
          - ocaml-version: 4.03.0
            os: ubuntu-latest
            skip_test: true
            configurator: true
          - ocaml-version: 4.02.3
            os: ubuntu-latest
            skip_test: true

    # We don't run tests on all versions of the Windows environment and on
    # 4.02.3 and 4.07.1 in other environments
    env:
      # Note that this environment variable is recognized as a string by GitHub
      # Actions, so the following doesn't actually work:
      #
      # if: env.SKIP_TEST
      #
      # To skip an action, the following should be used:
      # if: ${{ env.SKIP_TEST != "false" }}
      SKIP_TEST: ${{ matrix.skip_test }}
      OCAML_VERSION: ${{ matrix.ocaml-version }}
      OS: ${{ matrix.os }}
      CONFIGURATOR: ${{ matrix.configurator }}
      TEST_DEPS: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      # git user needs to be configured for the following tests:
      # otherlibs/build-info/test/run.t
      # test/blackbox-tests/test-cases/dune-project-meta/run.t
      # test/blackbox-tests/test-cases/subst/run.t
      # test/expect-tests/vcs_tests.ml
      - name: Set git user
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions-bot@users.noreply.github.com

      - name: Pin used packages to local directory
        run: opam exec -- ocaml .github/workflows/ci.ml pin

      # Install ocamlfind-secondary and ocaml-secondary-compiler, if needed
      - name: install dune dependencies
        run: opam exec -- ocaml .github/workflows/ci.ml install-deps-of-dune

      # dune doesn't have any additional dependencies so we can build it right
      # away this makes it possible to see build errors as soon as possible
      - name: compile dune
        run: opam exec -- make dune.exe

      - name: install deps of test suite
        run: opam exec -- ocaml .github/workflows/ci.ml install-deps-of-test
        if: env.SKIP_TEST != 'true'

      - name: run test suite
        run: opam exec -- ocaml .github/workflows/ci.ml test
        if: env.SKIP_TEST != 'true'

      - name: build configurator
        run: opam install ./dune-configurator.opam
        if: env.CONFIGURATOR == 'true'
